services:
  enterprise-portal:
    image: hacktifytechnologies/enterprise-portal:1.0
    container_name: enterprise-portal
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    restart: unless-stopped
